### PR TITLE
Fixed issue with typed builder on phantom data

### LINKED ISSUE #79: Unit test failing on AqlQueryBuilder
Hey @fMeow , how are you doing ? :smile: 

I am still playing with Rust :laughing: 

But I got an issue today and I am not sure why. I did updated arangor to 0.5.0 since I am using the latest `actix-web` now.

Here is the error when I want to use `arangors 0.5.0`  or unit test it : 

image

Did somebody sae that 0.5.0 tests were failing ?

### PR DESCRIPTION
**Pull request by ManevilleF**
Closes #79 

Also:
- Fixed some clippy warnings

### CODE REVIEW

File: tests/connection.rs [hunk 1]
```diff
@@ -45,7 +45,7 @@ async fn test_get_url() {
     let conn = Connection::establish_jwt(&host, &user, &password)
         .await
         .unwrap();
-    let url = conn.url().clone().into_string();
+    let url: String = conn.url().clone().into();
```
Comment (ManevilleF) [inline tests/connection.rs:48]: Fixed deprecation warning of the `into_string` method

File: src/response.rs [hunk 2]
```diff
@@ -49,9 +49,9 @@ pub(crate) enum Response<T> {
     Err(ArangoError),
 }
 
-impl<T> Into<Result<T, ArangoError>> for Response<T> {
-    fn into(self) -> Result<T, ArangoError> {
-        match self {
+impl<T> From<Response<T>> for Result<T, ArangoError> {
```
Comment (ManevilleF) [inline src/response.rs:52]: Clippy prefers `From` implementations

File: src/connection/mod.rs [hunk 3]
```diff
@@ -349,7 +349,7 @@ impl<C: ClientExt> GenericConnection<C, Normal> {
         password: T,
     ) -> Result<String, ClientError> {
         #[derive(Deserialize)]
-        struct JWT {
+        struct Jwt {
```
Comment (ManevilleF) [inline src/connection/mod.rs:352]: Clippy prefers this syntax

File: src/collection/mod.rs [hunk 4]
```diff
@@ -134,7 +134,7 @@ impl<'a, C: ClientExt> Collection<C> {
     /// characters only. Please refer to Naming Conventions in ArangoDB for more
     /// information on valid collection names.
     pub fn name(&self) -> &str {
-        &self.name.as_str()
+        self.name.as_str()
```
Comment (ManevilleF) [inline src/collection/mod.rs:137]: The borrowing was not needed

File: src/aql.rs [hunk 5]
```diff
@@ -150,7 +150,7 @@ impl<'a, __query, __count, __batch_size, __cache, __memory_limit, __ttl, __optio
                 ttl,
                 options,
             ),
-            _phantom: self._phantom,
+            phantom: self.phantom,
```
Comment (ManevilleF) [inline src/aql.rs:153]: `typed_builder` 0.9.1 requires this change

**Comment by ManevilleF** [comment]
@fMeow the test failing on revision doesn't happen on ArangoDB 3.7.x and appears on 3.8.0
